AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template for an Application Load Balancer

Parameters:
  VPCStackName:
    Type: String
    Description: Name of the VPC stack
    Default: BankCoreNetwork
  CertificateStackName:
    Type: String
    Description: Name of the Certificate stack
    Default: BankCoreCertificate

Resources:
  IngressALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${AWS::StackName}-IngressALB'
      Scheme: internet-facing
      Type: application
      Subnets:
        Fn::Split:
          - ','
          - Fn::ImportValue:
              !Sub '${VPCStackName}-PublicSubnetIds'
      SecurityGroups:
        - !Ref IngressALBSecurityGroup
      LoadBalancerAttributes:
        - Key: idle_timeout.timeout_seconds
          Value: '120'

  IngressALBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub '${AWS::StackName} Ingress ALB Security Group'
      VpcId:
        Fn::ImportValue:
          !Sub '${VPCStackName}-VPCId'

  IngressListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: fixed-response
          FixedResponseConfig:
            StatusCode: '404'
            ContentType: text/plain
            MessageBody: "Page Not Found"
      LoadBalancerArn:
        Ref: IngressALB
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn:
            Fn::ImportValue:
              !Sub '${CertificateStackName}-CertificateArn'
