AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  DomainName:
    Type: String
    Description: Domain that we assume to be hosted in Route53
    Default: example.com
  HostedZoneId:
    Type: String
    Description: Hosted Zone ID
    Default: Zxxxxxxxxxxxx

Outputs:
  CertificateArn:
    Description: Certificate ARN
    Export:
      Name: !Sub '${AWS::StackName}-CertificateArn'
    Value: !Ref Certificate
  CertificateDomain:
    Description: Certificate Domain
    Export:
      Name: !Sub '${AWS::StackName}-CertificateDomain'
    Value: !Ref DomainName

Resources:
  Certificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub '*.dev.${DomainName}'
        - !Sub '*.uat.${DomainName}'
        - !Sub '*.stg.${DomainName}'
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub '*.dev.${DomainName}'
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub '*.uat.${DomainName}'
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub '*.stg.${DomainName}'
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-Certificate'
