AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VPCStackName:
    Type: String
    Description: Name of the VPC stack
    Default: BankCoreNetwork

Resources:
  EKSCluster:
    Type: 'AWS::EKS::Cluster'
    Properties:
      Name: !Sub '${AWS::StackName}-EKS'
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds:
          - !Ref EKSSecurityGroupId
        SubnetIds:
          Fn::Split:
            - ','
            - Fn::ImportValue:
                !Sub '${VPCStackName}-PrivateSubnetIds'

  NodeGroup1:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: !Ref EKSCluster
      NodegroupName: !Sub '${AWS::StackName}-NodeGroup1'
      NodeRole: !GetAtt EKSNodegroupRole.Arn
      CapacityType: SPOT
      ScalingConfig:
        MinSize: 1
        MaxSize: 5
        DesiredSize: 2
      Subnets:
        Fn::Split:
          - ','
          - Fn::ImportValue:
              !Sub '${VPCStackName}-PrivateSubnetIds'
      InstanceTypes:
        - t3.large
        - t3.xlarge
        - c5.large
        - c5.xlarge

  EKSSecurityGroupId:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub '${AWS::StackName} Control Plane Security Group'
      VpcId:
        Fn::ImportValue:
          !Sub '${VPCStackName}-VPCId'

  EKSClusterRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${AWS::StackName}-EKSClusterRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy

  EKSNodegroupRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${AWS::StackName}-EKSNodeRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly